name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_DEPLOYMENT_TOKEN}}
